### ISSUE TITLE
Spark RDD throw index out of bound exception when there after split the row and row contains null

### ISSUE THREAD

**Issue by adnanrahin** [adnanrahin/Apache-Spark-Complete-Reference#1]
21/09/03 04:44:24 ERROR Executor: Exception in task 5.0 in stage 0.0 (TID 5)
java.lang.ArrayIndexOutOfBoundsException: Index 26 out of bounds for length 26
	at org.flight.analysis.FlightDelaysAndCancellations$.$anonfun$main$2(FlightDelaysAndCancellations.scala:48)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at org.apache.spark.rdd.RDD.$anonfun$foreach$2(RDD.scala:1012)
	at org.apache.spark.rdd.RDD.$anonfun$foreach$2$adapted(RDD.scala:1012)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2236)

**Comment by adnanrahin** [comment]
**flightsCsvRead.map(row => row.split(",", -1))** adding "-1" to split function will ignore null.
