### ISSUE TITLE
Perform Transformation of RDD inside another RDD

### ISSUE THREAD

**Issue by adnanrahin** [adnanrahin/Apache-Spark-Complete-Reference#5]
(2) When a Spark Streaming job recovers from checkpoint, this exception will be hit if a reference to an RDD not defined by the streaming job is used in DStream operations. For more information, See SPARK-13758.
	at org.apache.spark.rdd.RDD.sc(RDD.scala:102)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.filter(RDD.scala:438)
	at org.flight.analysis.FlightDelaysAndCancellations$.$anonfun$findTotalDistanceFlownEachAirline$5(FlightDelaysAndCancellations.scala:224)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.catalyst.expressions

**Comment by adnanrahin** [comment]
Spark Left Out join, allow us to map to different RDD, and allows us to search in Key's in one RDD to Another RDD.
